// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
import Link from 'next/link'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        
      >
        <nav>
          <Link href={'/docs/button'}>Button</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
